In [2]:
import numpy as np
import scipy.io as sio
import matplotlib.pyplot as plt
import math
import pandas as pd
import seaborn as sns
from sklearn.utils import shuffle
%matplotlib inline
plt.style.use('default')
line_markers = ['-.','-,','-o','-v','-^','-<','->','-1','-2','-3','-4','-s','-p','-*','-h','-H','-+','-x','-D','-d','-|','-_']
line_markers = ['*','h','<','4','x','d','|','_']

root = './'

In [2]:
name = 'ECCV_final_Imagenet_ssil_0_memsz_5000_base_50_step_50_batch_128_epoch_100_replay_16_factor_5.mat'
result = sio.loadmat(name)
top_1 = result['all'][0][0][0][0]
top_5 = result['all'][0][0][1][0]

print(top_1)
print(sum(top_1)/20)
print(top_5)
print(sum(top_5)/20)

name = 'prev_results/RESULT_Imagenet_er_0_memsz_5000_alpha_1_beta_0.0001_base_50_replay_16_batch_128_epoch_100_factor_5_RingBuffer_CE_lr_change.mat'
result = sio.loadmat(name)
top_1 = result['all'][0][0][0][0]
top_5 = result['all'][0][0][1][0]

print(top_1)
print(sum(top_1)/20)
print(top_5)
print(sum(top_5)/20)




[86.68       77.6        70.56       63.46       59.64       55.52666667
 53.36571429 50.95       48.13777778 45.916      44.32       42.59333333
 41.52615385 40.84571429 39.59733333 38.295      37.34823529 36.06888889
 35.46315789 35.27      ]
50.15819878032184
[97.32       94.36       90.54666667 87.47       84.608      81.81333333
 80.15428571 78.56       76.51111111 74.912      73.63636364 71.56
 70.67692308 69.87428571 68.83733333 67.3325     66.33882353 64.82444444
 64.15789474 63.662     ]
76.35779826485003
[86.36       78.66       70.10666667 63.62       59.584      55.41333333
 53.48571429 50.805      48.24888889 46.644      44.60363636 42.88666667
 41.93230769 40.48857143 39.66666667 38.655      37.34823529 35.94444444
 35.49684211 34.974     ]
50.24619869181386
[97.32       94.26       90.93333333 87.25       84.552      81.78666667
 80.15428571 78.555      76.67111111 74.856      73.64363636 71.64333333
 70.64615385 69.84       68.592      67.2825     65.95764706 64.6422222

In [3]:
name = 'ECCV_final_Imagenet_ssil_0_memsz_5000_base_100_step_100_batch_128_epoch_100_replay_32_factor_5.mat'
result = sio.loadmat(name)
top_1 = result['all'][0][0][0][0]
top_5 = result['all'][0][0][1][0]

print(top_1)
print(sum(top_1)/10)
print(top_5)
print(sum(top_5)/10)

name = 'prev_results/RESULT_Imagenet_er_0_memsz_5000_alpha_1_beta_0.0001_base_100_replay_32_batch_128_epoch_100_factor_5_RingBuffer_CE_lr_change.mat'
result = sio.loadmat(name)
top_1 = result['all'][0][0][0][0]
top_5 = result['all'][0][0][1][0]

print(top_1)
print(sum(top_1)/10)
print(top_5)
print(sum(top_5)/10)





[85.9        70.61       62.1        55.51       50.356      46.18333333
 42.98857143 41.005      38.76222222 35.752     ]
52.916712698412695
[96.2        90.66       85.50666667 81.52       78.088      74.47333333
 71.82571429 69.33       66.78222222 64.746     ]
77.91319365079366
[86 70 62 55 50 46 43 41 38 35]
52.6
[96 91 85 81 77 74 71 69 67 64]
77.5


In [4]:
name = 'ECCV_final_Imagenet_ssil_0_memsz_5000_base_200_step_200_batch_128_epoch_100_replay_64_factor_5.mat'
result = sio.loadmat(name)
top_1 = result['all'][0][0][0][0]
top_5 = result['all'][0][0][1][0]

print(top_1)
print(sum(top_1)/5)
print(top_5)
print(sum(top_5)/5)

name = 'prev_results/RESULT_Imagenet_er_0_memsz_5000_alpha_1_beta_0.0001_base_200_replay_64_batch_128_epoch_100_factor_5_RingBuffer_CE_lr_change.mat'
result = sio.loadmat(name)
top_1 = result['all'][0][0][0][0]
top_5 = result['all'][0][0][1][0]

print(top_1)
print(sum(top_1)/5)
print(top_5)
print(sum(top_5)/5)

[82.01       63.83       51.12666667 43.1275     36.424     ]
55.30363333333334
[94.68       85.51       77.98333333 70.7775     65.676     ]
78.92536666666666
[82.38  64.27  50.8   42.715 36.404]
55.3138
[94.34       85.735      77.80333333 70.8975     65.678     ]
78.89076666666666


In [5]:
name = 'ECCV_final_Imagenet_ssil_0_memsz_10000_base_100_step_100_batch_128_epoch_100_replay_32_factor_5.mat'
result = sio.loadmat(name)
top_1 = result['all'][0][0][0][0]
top_5 = result['all'][0][0][1][0]

print(top_1)
print(sum(top_1)/10)
print(top_5)
print(sum(top_5)/10)

name = 'prev_results/RESULT_Imagenet_er_0_memsz_10000_alpha_1_beta_0.0001_base_100_replay_32_batch_128_epoch_100_factor_5_RingBuffer_CE_lr_change.mat'
result = sio.loadmat(name)
top_1 = result['all'][0][0][0][0]
top_5 = result['all'][0][0][1][0]

print(top_1)
print(sum(top_1)/10)
print(top_5)
print(sum(top_5)/10)

[85.9        72.87       64.93333333 59.2        54.728      51.07
 48.22857143 46.4075     44.08222222 41.658     ]
56.907762698412704
[96.2        92.06       87.18666667 83.73       81.004      77.97333333
 75.59142857 73.77       71.66888889 69.746     ]
80.89303174603174
[85 72 65 59 54 51 47 46 43 41]
56.3
[96 91 87 84 81 77 75 73 71 69]
80.4


In [6]:
name = 'ECCV_final_Imagenet_ssil_0_memsz_20000_base_100_step_100_batch_128_epoch_100_replay_32_factor_5.mat'
result = sio.loadmat(name)
top_1 = result['all'][0][0][0][0]
top_5 = result['all'][0][0][1][0]

print(top_1)
print(sum(top_1)/10)
print(top_5)
print(sum(top_5)/10)

name = 'prev_results/RESULT_Imagenet_er_0_memsz_20000_alpha_1_beta_0.0001_base_100_replay_32_batch_128_epoch_100_factor_5_RingBuffer_CE_lr_change.mat'
result = sio.loadmat(name)
top_1 = result['all'][0][0][0][0]
top_5 = result['all'][0][0][1][0]

print(top_1)
print(sum(top_1)/10)
print(top_5)
print(sum(top_5)/10)

[85.9        73.84       66.68666667 61.9        57.716      54.52333333
 51.94285714 49.79       48.15555556 45.614     ]
59.60684126984127
[96.2        92.3        88.47333333 85.96       83.472      80.82666667
 78.88285714 77.0175     74.93111111 73.514     ]
83.15774682539683
[86 73 66 61 57 55 52 50 48 45]
59.3
[96 92 88 85 83 81 79 77 75 73]
82.9


In [7]:
name = 'ECCV_rebuttal_Imagenet_bic_0_memsz_20000_alpha_1_beta_0.0001_base_100_replay_32_batch_256_epoch_100_factor_1_RingBuffer_CE.mat'
result = sio.loadmat(name)
top_1 = result['all'][0][0][0][0]
top_5 = result['all'][0][0][1][0]

print(top_1)
print(top_5)

print(sum(top_5[1:])/9)

[84.98       76.28       67.24666667 58.515      52.212      46.78
 41.85714286 36.4475     32.95555556 29.506     ]
[96.26       92.86       89.56       86.475      83.476      80.46333333
 77.15714286 73.1275     69.38888889 66.112     ]
79.846651675485


In [12]:
name = 'ECCV_final_Imagenet_bic_0_memsz_20000_base_100_step_100_batch_256_epoch_100.mat'
result = sio.loadmat(name)
top_1 = result['all'][0][0][0][0]
top_5 = result['all'][0][0][1][0]

print(top_1)
print(top_5)

print(sum(top_5[1:])/9)

[85.32       76.82       70.34       62.89       56.896      51.24
 47.81714286 44.23       41.09111111 37.928     ]
[95.78       92.97       90.33333333 87.29       84.228      80.63
 77.84571429 74.915      71.91555556 69.244     ]
81.04128924162256


In [13]:
name = 'ECCV_final_Imagenet_bic_0_memsz_20000_base_100_step_100_batch_256_epoch_100.mat'
result = sio.loadmat(name)
top_1 = result['all'][0][0][0][0]
top_5 = result['all'][0][0][1][0]

print(top_1)
print(top_5)

print(sum(top_5[1:])/9)

[84.72 77.96 73.08]
[96.14       93.37       90.86666667]
20.47074074074074
